### ISSUE TITLE
Memory leaks when wrapped classes used as arguments to msg_send!

### ISSUE THREAD

**Issue by scoopr** [SSheldon/rust-objc-foundation#9]
I was tracking down some memory leaks in another project, that were reported by Instruments, but I could also see with `leaks`.

It seems, that using the wrapper struct directly as an argument for `msg_send!`, results in a leak. I observe this with adding a line to the `test_is_equal` of the `NSObject` wrapper like this: `unsafe { msg_send![obj1, isEqual:obj1] }`. I then see the leak with running something like `cargo test --no-run && leaks -atExit -- ./target/debug/objc_foundation-b902b09ce3d0a74a` (the atExit might require some symlink to be made).

It would seem that the object actually gets moved in (if I duplicate that added line, the compiler says so), but then it doesn't get dropped? I don't quite follow what happens behind all these macros. I do see that the wrapped method calls themselves call `msg_send!´, and it doesn't seem leak then..

I don't see that much documentation that shows if the wrapped structs are meant to be used in a random `msg_send!` anyway, but I don't see how else would these be used, unless everything is wrapped with these kind of helpers structs.

**Comment by SSheldon** [comment]
Closing this in favor of SSheldon/rust-objc#80, where further discussion is happening!
